CONFIG.SAMPLE_RATE = 1000;

CONFIG.SCANS_AVAILABLE_FUNCTION_COUNT = 100;
CONFIG.SCANS_REQUIRED_FUNCTION_COUNT = 1000;

CONFIG.PRACTICE_MODE = true;
CONFIG.EXPERIMENT_MODE = ~CONFIG.PRACTICE_MODE;

CONFIG.PRACTICE_MODE_NUMBER_OF_FORCE_PRACTICES = 5;
CONFIG.PRACTICE_MODE_MAGNITUDE_OF_FORCE_PRACTICES = 0.5; % N
CONFIG.PRACTICE_MODE_NUMBER_OF_VELOCITY_PRACTICES = 5;
CONFIG.PRACTICE_MODE_MAGNITUDE_OF_VELOCITY_PRACTICES = 30; % mm/s

