%% Auto-generated by Data Acquisition Toolbox Analog Input Recorder on 28-Aug-2021 18:15:20
%% Create DataAcquisition Object
% Create a DataAcquisition object for the specified vendor.

d = daq("ni");
%% Add Channels
% Add channels and set channel properties, if any.

addinput(d,"Dev1","ai0","Voltage");


%% Read Data to bias sensor
% Read the data in timetable format.
d.Rate = 1000;
d.ScansAvailableFcn =@(src, evt) plotData(src, evt);
d.ScansAvailableFcnCount = 100;

start(d, 'continuous');




function plotData(d, ~)

    data = read(d, d.ScansAvailableFcnCount, 'OutputFormat', 'Matrix');
    if mean(data) < -3
        
        disp("NOOO")
        
    end
end