pciDAQ = NIDevice("Dev1",...
							{"ai0", "ai1", "ai2", "ai3", "ai4", "ai5"},...
							"Voltage",...
							"Input");

usbDAQ = NIDevice("Dev2",...
				{"ai0", "ai1", "ai2", "ai3", "ai4", "ai5"},...
				"Voltage",...
				"Input");