pciDAQ = NIDevice("Dev1",...
				{"ai0", "ai1", "ai2", "ai3", "ai4", "ai5"},...
				"Voltage",...
				"Input");

usbDAQ1 = NIDevice("Dev2",...
				{"ai4", "ai12", "ai5"},...
				"Voltage",...
				"Input");

usbDAQ2 = NIDevice("Dev2",...
				{"ao1"},...
				"Voltage",...
				"Output");

usbDAQ = usbDAQ1 + usbDAQ2;

niHandler = NIHandler();

niHandler.addInput(pciDAQ);
niHandler.addInput(usbDAQ);

forceSensor = ForceSensor;
accelerometer = Accelerometer;
signalGenerator = SignalGenerator;
fingerTracker = FingerTracker;