CONFIG.SAMPLE_RATE = 10000;

CONFIG.SCANS_AVAILABLE_FUNCTION_COUNT = 1000;

CONFIG.PRACTICE_MODE = false;

CONFIG.PRACTICE_MODE_NUMBER_OF_FORCE_PRACTICES = 2;
CONFIG.PRACTICE_MODE_MAGNITUDE_OF_FORCE_PRACTICES = 0.5; % N
CONFIG.PRACTICE_MODE_NUMBER_OF_VELOCITY_PRACTICES = 1;
CONFIG.PRACTICE_MODE_MAGNITUDE_OF_VELOCITY_PRACTICES = 30; % mm/s

CONFIG.EXPERIMENT_MODE = ~CONFIG.PRACTICE_MODE;
CONFIG.DESIRED_NORMAL_FORCE = 0.75;
CONFIG.DESIRED_SLIDING_VELOCITY = 4;
